# GoReleaser configuration for rdma_exporter.
# See https://goreleaser.com/ for documentation.
version: 2
project_name: rdma_exporter

release:
  github:
    owner: yuuki
    name: rdma_exporter

builds:
  - id: rdma_exporter
    main: .
    binary: rdma_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}

archives:
  - id: tgz
    ids:
      - rdma_exporter
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
      - deploy/systemd/rdma_exporter.service

dockers:
  - id: rdma_exporter_amd64
    ids:
      - rdma_exporter
    image_templates:
      - ghcr.io/yuuki/rdma_exporter:{{ .Version }}-amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    dockerfile: deploy/docker/Dockerfile.binary
    goarch: amd64
    goos: linux
  - id: rdma_exporter_arm64
    ids:
      - rdma_exporter
    image_templates:
      - ghcr.io/yuuki/rdma_exporter:{{ .Version }}-arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
    dockerfile: deploy/docker/Dockerfile.binary
    goarch: arm64
    goos: linux

docker_manifests:
  - name_template: ghcr.io/yuuki/rdma_exporter:{{ .Version }}
    image_templates:
      - ghcr.io/yuuki/rdma_exporter:{{ .Version }}-amd64
      - ghcr.io/yuuki/rdma_exporter:{{ .Version }}-arm64
  - name_template: ghcr.io/yuuki/rdma_exporter:latest
    image_templates:
      - ghcr.io/yuuki/rdma_exporter:{{ .Version }}-amd64
      - ghcr.io/yuuki/rdma_exporter:{{ .Version }}-arm64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  use: git
