# GoReleaser configuration for rdma_exporter.
# See https://goreleaser.com/ for documentation.
version: 2
project_name: rdma_exporter

builds:
  - id: rdma_exporter
    main: .
    binary: rdma_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}

archives:
  - id: tgz
    ids:
      - rdma_exporter
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  use: git
