# syntax=docker/dockerfile:1.7
ARG ALPINE_VERSION=3.20

FROM alpine:${ALPINE_VERSION}
RUN addgroup -S rdma_exporter \
  && adduser -S -G rdma_exporter rdma_exporter \
  && apk add --no-cache ca-certificates
COPY rdma_exporter /usr/local/bin/rdma_exporter
USER rdma_exporter
EXPOSE 9879
ENTRYPOINT ["/usr/local/bin/rdma_exporter"]
CMD ["--listen-address=:9879","--metrics-path=/metrics","--health-path=/healthz"]
